require 'spec_helper'

# This spec was generated by rspec-rails when you ran the scaffold generator.
# It demonstrates how one might use RSpec to specify the controller code that
# was generated by Rails when you ran the scaffold generator.
#
# It assumes that the implementation code is generated by the rails scaffold
# generator.  If you are using any extension libraries to generate different
# controller code, this generated spec may or may not pass.
#
# It only uses APIs available in rails and/or rspec-rails.  There are a number
# of tools you can use to make these specs even more expressive, but we're
# sticking to rails and rspec-rails APIs to keep things simple and stable.
#
# Compared to earlier versions of this generator, there is very limited use of
# stubs and message expectations in this spec.  Stubs are only used when there
# is no simpler way to get a handle on the object needed for the example.
# Message expectations are only used when there is no simpler way to specify
# that an instance is receiving a specific message.

describe PmsController do

  # This should return the minimal set of attributes required to create a valid
  # Pm. As you add validations to Pm, be sure to
  # adjust the attributes here as well.
  let(:valid_attributes) { { "author" => "" } }

  # This should return the minimal set of values that should be in the session
  # in order to pass any filters (e.g. authentication) defined in
  # PmsController. Be sure to keep this updated too.
  let(:valid_session) { {} }

  describe "GET index" do
    it "assigns all pms as @pms" do
      pm = Pm.create! valid_attributes
      get :index, {}, valid_session
      assigns(:pms).should eq([pm])
    end
  end

  describe "GET show" do
    it "assigns the requested pm as @pm" do
      pm = Pm.create! valid_attributes
      get :show, {:id => pm.to_param}, valid_session
      assigns(:pm).should eq(pm)
    end
  end

  describe "GET new" do
    it "assigns a new pm as @pm" do
      get :new, {}, valid_session
      assigns(:pm).should be_a_new(Pm)
    end
  end

  describe "GET edit" do
    it "assigns the requested pm as @pm" do
      pm = Pm.create! valid_attributes
      get :edit, {:id => pm.to_param}, valid_session
      assigns(:pm).should eq(pm)
    end
  end

  describe "POST create" do
    describe "with valid params" do
      it "creates a new Pm" do
        expect {
          post :create, {:pm => valid_attributes}, valid_session
        }.to change(Pm, :count).by(1)
      end

      it "assigns a newly created pm as @pm" do
        post :create, {:pm => valid_attributes}, valid_session
        assigns(:pm).should be_a(Pm)
        assigns(:pm).should be_persisted
      end

      it "redirects to the created pm" do
        post :create, {:pm => valid_attributes}, valid_session
        response.should redirect_to(Pm.last)
      end
    end

    describe "with invalid params" do
      it "assigns a newly created but unsaved pm as @pm" do
        # Trigger the behavior that occurs when invalid params are submitted
        Pm.any_instance.stub(:save).and_return(false)
        post :create, {:pm => { "author" => "invalid value" }}, valid_session
        assigns(:pm).should be_a_new(Pm)
      end

      it "re-renders the 'new' template" do
        # Trigger the behavior that occurs when invalid params are submitted
        Pm.any_instance.stub(:save).and_return(false)
        post :create, {:pm => { "author" => "invalid value" }}, valid_session
        response.should render_template("new")
      end
    end
  end

  describe "PUT update" do
    describe "with valid params" do
      it "updates the requested pm" do
        pm = Pm.create! valid_attributes
        # Assuming there are no other pms in the database, this
        # specifies that the Pm created on the previous line
        # receives the :update_attributes message with whatever params are
        # submitted in the request.
        Pm.any_instance.should_receive(:update).with({ "author" => "" })
        put :update, {:id => pm.to_param, :pm => { "author" => "" }}, valid_session
      end

      it "assigns the requested pm as @pm" do
        pm = Pm.create! valid_attributes
        put :update, {:id => pm.to_param, :pm => valid_attributes}, valid_session
        assigns(:pm).should eq(pm)
      end

      it "redirects to the pm" do
        pm = Pm.create! valid_attributes
        put :update, {:id => pm.to_param, :pm => valid_attributes}, valid_session
        response.should redirect_to(pm)
      end
    end

    describe "with invalid params" do
      it "assigns the pm as @pm" do
        pm = Pm.create! valid_attributes
        # Trigger the behavior that occurs when invalid params are submitted
        Pm.any_instance.stub(:save).and_return(false)
        put :update, {:id => pm.to_param, :pm => { "author" => "invalid value" }}, valid_session
        assigns(:pm).should eq(pm)
      end

      it "re-renders the 'edit' template" do
        pm = Pm.create! valid_attributes
        # Trigger the behavior that occurs when invalid params are submitted
        Pm.any_instance.stub(:save).and_return(false)
        put :update, {:id => pm.to_param, :pm => { "author" => "invalid value" }}, valid_session
        response.should render_template("edit")
      end
    end
  end

  describe "DELETE destroy" do
    it "destroys the requested pm" do
      pm = Pm.create! valid_attributes
      expect {
        delete :destroy, {:id => pm.to_param}, valid_session
      }.to change(Pm, :count).by(-1)
    end

    it "redirects to the pms list" do
      pm = Pm.create! valid_attributes
      delete :destroy, {:id => pm.to_param}, valid_session
      response.should redirect_to(pms_url)
    end
  end

end
